services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: app_php
    restart: no
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/99-custom.ini
    networks:
      - app_news

  nginx:
    image: nginx:alpine
    container_name: app_nginx
    restart: no
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app_news

networks:
  app_news:
    driver: bridge
